### ISSUE TITLE
Square classifier training fails on missing quilt package

### ISSUE THREAD

**Issue by orenlivne** [gudbrandtandberg/ChessVision#11]
Hello!

- I don't see any pre-trained models available. If they are available for download, how do you download them?
- Note that install.sh is mentioned in the README but does not exist.
These are separate bugs that need to be fixed. So, for now I'm trying to retrain the model. I started with the square classifier. I'm running

cd ChessVision/ml/training
python train_square_classifier.py

This fails on the quilt package not being found

Traceback (most recent call last):
  File "/Users/olivne/oren/ChessVision/ml/training/train_square_classifier.py", line 10, in <module>
    from dataset_utils import get_validation_generator, get_training_generator, inverse_labels, get_class_weights, install_data
  File "/Users/olivne/oren/ChessVision/ml/training/dataset_utils.py", line 13, in <module>
    pieces = quilt.load(PIECES_PATH, hash="d28b23f6aa44126b23150d4108c1af7219f33fbbaa2f61b1c9152a9864f1c8dd")
  File "/Users/olivne/miniconda3/envs/chessvision/lib/python3.9/site-packages/quilt/tools/command.py", line 1355, in load
    node, pkgroot, info = _load(pkginfo, hash)
  File "/Users/olivne/miniconda3/envs/chessvision/lib/python3.9/site-packages/quilt/tools/command.py", line 1346, in _load
    raise CommandException("Package {package} not found.".format(package=package))
quilt.tools.command.CommandException: Package gudbrandtandberg/chesspieces not found.

Could you please advise? Thanks.

**Comment by gudbrandtandberg** [comment]
Hey. 

Thanks for the interest. I'll try to provide some useful answers. 

I am not really maintaining this project anymore, it was just a toy experiment really. So that's why it will not run out-of-the-box, and documentation is out of sync with code. Sorry about that. 

Anyway, I don't have any pretrained models available I'm afraid. But it's more fun to train your own anyway! A lot has happened to quilt since I was using it, but their legacy webpage should still be serving my dataset. Here is the [link to it](https://legacy.quiltdata.com/package/gudbrandtandberg/chesspieces). It should be possible to download the package from the quilt python library. Perhaps remove the hash I'm supplying? 

If you can't get it to work, there's another way. The squares training data is all in data/squares anyway, so you can just create a image folder datagenerator using the built in keras class.

Let me know if you have any more trouble.
